[package]
name = "cedar"
version = "0.1.0"
edition = "2021"
authors = ["Jude Peel <judepeel.dev@gmail.com>"]
repository = "https://github.com/jude-peel/cedar"


[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
crc32fast = "1.4.2"
